services:
  - type: web
    name: my-backend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /api/*
        destination: https://contact-manager-op0d.onrender.com/*
      - type: rewrite
        source: /*
        destination: /index.html
